version: '3'
services:
    dash_statistics_service:
      build: dash_statistics_service/.
      ports:
      - 5000:5000

    postgres:
      image: postgres:latest
      container_name: postgres
      restart: always
      env_file:
        - postgres-db/scripts/database.env
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-db/postgres-data:/var/lib/postgresql/data